wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/wallpapers-main/misc/windows-error.jpg
    fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
