
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/


################
### DEFAULTS ###
################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize
# Fix some dragging issues with XWayland
windowrule = match:class ^$ match:title ^$ match:xwayland 1 match:float 1 match:fullscreen 0 match:pin 0, no_initial_focus on


windowrule = match:class ^(org.kde.dolphin)$ match:title ^(Progress Dialog — Dolphin)$, float on
windowrule = match:class ^(org.kde.dolphin)$ match:title ^(Copying — Dolphin)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:class ^(firefox)$ match:title ^(Library)$, float on
windowrule = match:class ^(vlc)$, float on
windowrule = match:class ^(kvantummanager)$, float on
windowrule = match:class ^(qt5ct)$, float on
windowrule = match:class ^(qt6ct)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(org.kde.ark)$, float on
windowrule = match:class ^(Signal)$, float on # Signal-Gtk
windowrule = match:class ^(com.github.rafostar.Clapper)$, float on # Clapper-Gtk
windowrule = match:class ^(app.drey.Warp)$, float on # Warp-Gtk
windowrule = match:class ^(net.davidotek.pupgui2)$, float on # ProtonUp-Qt
windowrule = match:class ^(yad)$, float on # Protontricks-Gtk
windowrule = match:class ^(eog)$, float on # Imageviewer-Gtk
windowrule = match:class ^(io.github.alainm23.planify)$, float on # planify-Gtk
windowrule = match:class ^(io.gitlab.theevilskeleton.Upscaler)$, float on # Upscaler-Gtk
windowrule = match:class ^(com.github.unrud.VideoDownloader)$, float on # VideoDownloader-Gkk
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-applet)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, float on
windowrule = match:class ^(Perimeter81)$, float on
# windowrule = match:class ^(Perimeter81)$, stayfocused on
windowrule = match:class ^(Perimeter81)$ match:float 1, center on
windowrule = match:class ^(Harmony SASE)$, float on
# windowrule = match:class ^(Harmony SASE)$, stayfocused on
windowrule = match:class ^(Harmony SASE)$ match:float 1, center on
windowrule = match:class ^(org.freedesktop.impl.portal.desktop.gtk)$, opacity 0.90 0.90
windowrule = match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$, opacity 0.90 0.90
windowrule = match:class ^(Vivaldi-stable)$, tile on
windowrule = match:class ^(winbox.exe)$, tile on
windowrule = match:class ^(Codium)$ match:float 1, center on
# windowrule = match:class ^(OrcaSlicer)$, stayfocused on
# windowrule = match:class ^(OrcaSlicer)$, move onscreen cursor
# windowrule = match:class ^(OrcaSlicer)$ match:title ^()$, stayfocused on
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = match:float 0 match:onworkspace w[tv1], rounding 0
windowrule = match:float 0 match:onworkspace f[1], border_size 0
windowrule = match:float 0 match:onworkspace f[1], rounding 0
windowrule = match:class (clipse), float on
windowrule = match:title (satty), float on
windowrule = match:title (satty) match:float 1, center on
windowrule = match:class (clipse), size 622 652
windowrule = match:title (satty), size 75% 75%

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = match:namespace rofi, blur on
layerrule = match:namespace notifications, blur on
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace logout_dialog, blur on
