
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2
monitor=eDP-1, 2560x1600@120, 0x0, 1.25
monitor=HDMI-A-1, 1920x1080, -1920x200, 1
# monitor=DP-5, 1920x1080, -896x-1080, 1
# monitor=DP-6, 1920x1080, 1024x-1080, 1
monitor=desc:Dell Inc. DELL P2421DC JW9PR63, 2560x1440, -2560x-1440, 1
monitor=desc:Dell Inc. DELL P2421DC GYFPR63, 2560x1440, 0x-1440, 1
