#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
$HOME/.config/polybar/launch.sh
autorandr --change
feh --recursive --randomize --bg-center --image-bg "#24283b" ~/Pictures/backgrounds/desktop/tokyo-night/
picom &
pasystray &
source /etc/profile
export PATH="$HOME/.local/bin:$PATH"
export TERM=kitty
setxkbmap -layout cz -variant coder
brightnessctl --device='tpacpi::kbd_backlight' -q set 2

if [[ $(autorandr --current) | grep -q 'docked' ]]; then
    bspc wm --reorder-monitors eDP-1 DP-1-2 DP-1-3
elif [[ $(autorandr --current) | grep -q 'office-1440p' ]]; then
    bspc wm --reorder-monitors DP-1-8 eDP-1 DP-2
fi

wrkspc=0
bspc query --names --monitors | while read -r line; do
    bspc monitor $line -d $((wrkspc+1)) $((wrkspc+2)) $((wrkspc+3)) $((wrkspc+4)) $((wrkspc+5))
    wrkspc=$((wrkspc+5))
done

bspc config active_border_color \#e1acff
bspc config focused_border_color \#e1acff
bspc config normal_border_color \#1D2330

bspc config border_width       1
bspc config window_gap         10
bspc config top_padding        20
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
