# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  black: black
  blue: blue
  cyan: cyan
  darkGray: darkGray
  green: green
  lightBlue: lightBlue
  lightCyan: lightCyan
  lightGreen: lightGreen
  lightMagenta: lightMagenta
  lightRed: lightRed
  lightWhite: lightWhite
  lightYellow: lightYellow
  magenta: magenta
  red: red
  white: white
  yellow: yellow
secondary_prompt:
  template: "•   "
  foreground: p:darkGray
  background: transparent
transient_prompt:
  template: "❯ "
  background: transparent
  foreground_templates:
  - "{{if gt .Code 0}}p:red{{end}}"
  - "{{if eq .Code 0}}p:green{{end}}"
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: " {{ if .SSHSession }}\ueba9 {{ .UserName }} {{ .HostName }} {{ end }}"
    foreground: p:blue
    background: transparent
    type: session
    style: plain
  - properties:
      cache_duration: none
      style: full
    template: "{{ .Path }}"
    foreground: blue
    background: transparent
    type: path
    style: plain
  - properties:
      cache_duration: none
      display_default: true
    template: " \uf1d1 {{if .Namespace}}{{.Namespace}}@{{ end }}{{.Context}}"
    foreground: p:blue
    background: transparent
    type: kubectl
    style: plain
  - properties:
      branch_max_length: 25
      cache_duration: none
      fetch_status: true
      fetch_upstream_icon: true
    template: " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} "
    foreground: p:grey
    background: transparent
    type: git
    style: plain
  - properties:
      cache_duration: none
    template: " \uf0e7 "
    foreground: p:red
    background: transparent
    type: root
    style: plain
  newline: true
- type: rprompt
  segments:
  - properties:
      cache_duration: none
      display_mode: files
      fetch_package_manager: true
      home_enabled: false
    template: "\ue718 "
    foreground: p:green
    background: transparent
    type: node
    style: plain
  - properties:
      cache_duration: none
      fetch_version: false
    template: "\ue626 "
    foreground: p:blue
    background: transparent
    type: go
    style: plain
  - properties:
      cache_duration: none
      display_mode: environment
      fetch_version: false
      fetch_virtual_env: true
    template: "\ue235 {{ .Venv }}"
    foreground: p:yellow
    background: transparent
    type: python
    style: plain
  - properties:
      cache_duration: none
      threshold: 500
    template: "{{ .FormattedMs }}"
    foreground: yellow
    background: transparent
    type: executiontime
    style: plain
  - properties:
      cache_duration: none
    template: "{{ if lt .Percentage 80 }}bat {{ .Percentage }}%{{ if eq \"Charging\" .State.String }} charging{{ end }}{{ end }}"
    foreground: p:red
    background: transparent
    type: battery
    style: plain
    foreground_templates:
    - "{{if gt .Percentage 80}}p:green{{end}}"
    - "{{if gt .Percentage 30}}p:yellow{{end}}"
    - "{{if lt .Percentage 30}}p:red{{end}}"
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: ❯
    background: transparent
    type: text
    style: plain
    foreground_templates:
    - "{{if gt .Code 0}}p:red{{end}}"
    - "{{if eq .Code 0}}p:green{{end}}"
  newline: true
tooltips:
- properties:
    display_default: true
  trailing_diamond: 
  template: " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
  foreground: p:yellow
  background: transparent
  type: aws
  style: plain
  tips:
  - aws
- properties:
    display_default: true
  trailing_diamond: 
  template: " \ue7ad {{ .Project }} {{ if .Region }}@{{ .Region }}{{ end }} "
  foreground: p:blue
  background: transparent
  type: gcp
  style: plain
  tips:
  - gcp
version: 3
final_space: true
